<?php

/* trad pour les champs SQL */
$_trad['champ']['active'] = "Activer";
$_trad['champ']['adresse'] = "Adresse";
$_trad['champ']['capacite'] = "Capacité";
$_trad['champ']['categorie'] = "Categorie";
$_trad['champ']['cp'] = "Code Postal";
$_trad['champ']['description'] = "Description";
$_trad['champ']['email'] = "E-mail";
$_trad['champ']['gsm'] = "N°. portable";
$_trad['champ']['id_membre'] = "Identifiant";
$_trad['champ']['id_salle'] = "Identifiant";
$_trad['champ']['mdp'] = "Mot de passe";
$_trad['champ']['nom'] = "Nom";
$_trad['champ']['pays'] = "Pays";
$_trad['champ']['photo'] = "Photo";
$_trad['champ']['pos'] = "Position";
$_trad['champ']['prenom'] = "Prénom";
$_trad['champ']['pseudo'] = "Pseudonime";
$_trad['champ']['rapel'] = "Option";
$_trad['champ']['sexe'] = "Sexe";
$_trad['champ']['statut'] = "Statut";
$_trad['champ']['telephone'] = "N°. téléphone";
$_trad['champ']['titre'] = "Nom";
$_trad['champ']['valide'] = "Valider";
$_trad['champ']['ville'] = "Ville";

/* trad pour valeurs par defaut dans les formulaires */
$_trad['defaut']['ajouter'] = "Ajouter";
$_trad['defaut']['capacite'] = "Capacité";
$_trad['defaut']['cp'] = "99000";
$_trad['defaut']['description'] = "Description...";
$_trad['defaut']['gsm'] = "06 12 34 56 78";
$_trad['defaut']['Inscription'] = "S'Inscrire";
$_trad['defaut']['MiseAJ'] = "Mettre à jour";
$_trad['defaut']['modifier'] = "Mettre à jour mes informations";
$_trad['defaut']['Monnom'] = "Mon nom";
$_trad['defaut']['Monprenom'] = "Mon prenom";
$_trad['defaut']['MotPasse'] = "MotPasse!";
$_trad['defaut']['Ouhabite'] = "Ou j'habite";
$_trad['defaut']['photo'] = "Photo";
$_trad['defaut']['SeConnecter'] = "Se Connecter";
$_trad['defaut']['telephone'] = "01 89 76 43 21";
$_trad['defaut']['ville'] = "Mont...";

/* trad des messages d'erreurs dans les formulaires */
$_trad['erreur']['acces'] = " <span class='alert'>Désoles Vous avez épuisée vos tentatives de connexion authorises<br>Veuillez quiter votre navigateur et venir plus tard !</span>";
$_trad['erreur']['aphanumeriqueSansSpace'] = " Caractere acceptés: A à Z et 0 à 9 sans espaces ";
$_trad['erreur']['ATTENTIONErreurSurRequeteSQL'] = "<span style='color:red'>ATTENTION! Erreur sur la requete SQL</span><br /><b>Message : </b>";
$_trad['erreur']['ATTENTIONfaitQuoiAvec'] = " ATTENTION !!!! Vous fait Quoi avec ";
$_trad['erreur']['ATTENTIONImpossibleFermerConnexionBDD'] = "<span style='color:red'>ATTENTION! Il est impossible de fermer la connexion à la BDD</span><br /><b>Message : </b>";
$_trad['erreur']['caracteres'] = " caracteres ";
$_trad['erreur']['controlTelephone'] = " Au moins un N° de téléphone doit être renseigné ";
$_trad['erreur']['corrigerErreurDans'] = " Merci de rectifier ";
$_trad['erreur']['doitContenir'] = " doit contenir ";
$_trad['erreur']['doitContenirEntre'] = " doit contenir entre ";
$_trad['erreur']['emailexistant'] = " <span class='alert'>Ce mail existe déjàs !</span>";
$_trad['erreur']['erreurConnexion'] = "<span class='alert'>Nous ne pouvons pas vous identifier <br>Merci de saisir à nouveau vos informations </span>";
$_trad['erreur']['erreurDansDimensionsImage']= "Erreur dans les dimensions de l'image !";
$_trad['erreur']['erreurInterneEmpecheUplaodImage'] = "Une erreur interne a empêché l'uplaod de l'image";
$_trad['erreur']['extensionFichierEstIncorrecte'] = "L'extension du fichier est incorrecte !";
$_trad['erreur']['fichierUploaderNestPasUneImage'] = "Le fichier à uploader n'est pas une image !";
$_trad['erreur']['inconueConnexion'] = "<span class='alert'>Une erreur est survenue </span>";
$_trad['erreur']['installData'] = "<span style='color:red'>ERREUR FATAL!</span>";
$_trad['erreur']['leRepertoireNePeutEtreCree'] = "Erreur : le répertoire cible ne peut-être créé ! Vérifiez que vous diposiez des droits suffisants pour le faire ou créez le manuellement !";
$_trad['erreur']['minimumAphaNumerique'] = " Il doit avoir un nombre de minimum ";
$_trad['erreur']['nonVide'] = " Il ne doit pas étre vide ";
$_trad['erreur']['NULL'] = $_trad['erreur']['inconueConnexion'] . "<br/>L'information que vous demandez n'existe pas!";
$_trad['erreur']['obligatoire'] = " est obligatoire ";
$_trad['erreur']['problemeLorsUpload'] = "Problème lors de l'upload !";
$_trad['erreur']['pseudoIndisponble'] = " <span class='alert'>Pseudo indisponible !</span> ";
$_trad['erreur']['queDesChiffres'] = " Il doit comptenir que des chiffres ";
$_trad['erreur']['surLe'] = " Erreur sur ";
$_trad['erreur']['uneErreurEstSurvenue'] = " Une erreur est survenue lors de votre connexion!";
$_trad['erreur']['veuillezDeRectifier'] = " Merci de rectifier le ";
$_trad['erreur']['veuillezRemplirFormulaire'] = "Veuillez remplir le formulaire svp !";
$_trad['erreur']['vousAvezOublieDeRectifier'] = " Vous avez oublié de rectifier le ";
$_trad['erreur']['vousAvezUneErreurDans'] = " Vous avez une erreur dans  ";
$_trad['erreur']['vousDevezChoisireUneOption'] = " Vous devez choisir une option ";

/* trad pour les menus */
$_trad['nav']['actif'] = "Connexion";
$_trad['nav']['ADMIN'] = "ADMIN";
$_trad['nav']['backoffice'] = "Panneau d'admin"; 
$_trad['nav']['boutique'] = "Boutique"; 
$_trad['nav']['cgv'] = "C.G.V"; 
$_trad['nav']['conditionsGeneralesVente'] = "Conditions Générales de Vente";
$_trad['nav']['contact'] = "Contact"; 
$_trad['nav']['detail'] = "Fiche"; 
$_trad['nav']['detailDuProduit'] = "Detail du produit";
$_trad['nav']['editerSalles'] = "Fiche salle";
$_trad['nav']['ficheMembre'] = "Fiche Membres"; 
$_trad['nav']['ficheSalles'] = "Fiche Salle"; 
$_trad['nav']['gestionSalles'] = "Salles";
$_trad['nav']['home'] = "Accueil"; 
$_trad['nav']['inscription'] = "Inscription"; 
$_trad['nav']['locationDesSalles'] = "Location des salles";
$_trad['nav']['mdpperdu'] = "Récuparation du mot de pase";
$_trad['nav']['mentions'] = "Mentions légales"; 
$_trad['nav']['mentionsLegales'] = "Mentions légales";
$_trad['nav']['mesAchats'] = "Mes achats";
$_trad['nav']['mettreJourMesInformations'] = "Mettre à jour mes informations";
$_trad['nav']['mjprofil'] = "Mise a jour"; 
$_trad['nav']['monProfil'] = "Mon Profil";
$_trad['nav']['MotDePasseOublie'] = "Mot de passe Oublié";
$_trad['nav']['newsletter'] = "S'inscrire à la newsletter"; 
$_trad['nav']['nousContacter'] = "Nous Contacter"; 
$_trad['nav']['out'] = "Déconnexion";
$_trad['nav']['panier'] = "Panier"; 
$_trad['nav']['plan'] = "Plan du site"; 
$_trad['nav']['profil'] = "Voir votre profil"; 
$_trad['nav']['recherche'] = "Recherche";
$_trad['nav']['reservation'] = "Réservation";
$_trad['nav']['resultatDeVotreRecherche'] = "Resultat de votre recherche";
$_trad['nav']['salles'] = "Salles"; 
$_trad['nav']['seInscrire'] = "S'inscrire";
$_trad['nav']['toutesNosOffres'] = "Toutes nos offres";
$_trad['nav']['users'] = "Membres"; 
$_trad['nav']['ventes'] = "Commandes";

/* trad pour les titres des pages */
$_trad['titre']['actif'] = "";
$_trad['titre']['backoffice'] = "administration";
$_trad['titre']['boutique'] = "boutique";
$_trad['titre']['cgv'] = "Conditions Générales de Vente";
$_trad['titre']['changermotpasse'] = "Changer le mot de passe";
$_trad['titre']['connexion'] = "se connecter";
$_trad['titre']['contact'] = "contact";
$_trad['titre']['detail'] = "Detail du produit";
$_trad['titre']['editerSalles'] = "Modifier une salle";
$_trad['titre']['erreur404'] = "ERREUR 404";
$_trad['titre']['ficheMembre'] = "Fiche Membres";
$_trad['titre']['ficheSalles'] = "Fiche Salle LOKISALLE"; 
$_trad['titre']['gestionSalles'] = "Gestion des salles";
$_trad['titre']['home'] = "Location des salles";
$_trad['titre']['inscription'] = "S'inscrire";
$_trad['titre']['mdpperdu'] = "Mot de passe Oublié";
$_trad['titre']['mentions'] = "Mentions légales";
$_trad['titre']['mjprofil'] = "Mettre à jour Mes Informations";
$_trad['titre']['newsletter'] = "Newsletter";
$_trad['titre']['out'] = "";
$_trad['titre']['panier'] = "Mes Achats";
$_trad['titre']['plan'] = "Nos Rubriques";
$_trad['titre']['profil'] = "Profil";
$_trad['titre']['recherche'] = "Resultat de votre recherche";
$_trad['titre']['reservation'] = "Toutes nos offres";
$_trad['titre']['salles'] = "LOKISALLE"; 
$_trad['titre']['users'] = "Membres";
$_trad['titre']['validerIncription'] = "Validation d'inscription";
$_trad['titre']['ventes'] = "Commandes";

/* trad pour les Valeurs des options BDD */
$_trad['value']['ADM'] = "ADMIN.";
$_trad['value']['C'] = "Conferences";
$_trad['value']['COL'] = "INT";
$_trad['value']['F'] = "Fêtes";
$_trad['value']['f'] = "Femminin";
$_trad['value']['m'] = "Masculin";
$_trad['value']['MEM'] = "MEMBRE";
$_trad['value']['R'] = "Reunions";
$_trad['value']['on'] = "Se rappeler de moi";

/* trad pour les autres textes */
$_trad['activer'] = "Activer";
$_trad['admin'] = "Adminitrateur";
$_trad['annuler'] = "Annuler";
$_trad['ATTENTIONErreurRequeteSQL'] = "<span style='color:red'>ATTENTION! Erreur sur la requete SQL</span><br /><b>Message : </b>";
$_trad['ATTENTIONImpossibleFermerConnexionBDD'] = "<span style='color:red'>ATTENTION! Il est impossible de fermer la connexion à la BDD</span><br /><b>Message : </b>";
$_trad['delete'] = "Supprimer";
$_trad['demandeDeMotPasse'] = 'Demande de Mot de passe';
$_trad['enConstruccion'] =  "En cours de réalisation!";
$_trad['enlever'] = "Enlever";
$_trad['ERROR404'] = "La page demandé n'existe pas!";
$_trad['ERRORSaisie'] = "Merci de Corriger le(s) erreur(s) dans le formulaire";
$_trad['indefinie'] = "<span class='alert'>Indéfinie</span>";
$_trad['inscriptionLokisalle'] = "Inscription Lokisalle";
$_trad['inscrivezVous'] = " Inscrivez-vous ";
$_trad['laRubrique'] = "La rubrique ";
$_trad['lesModificationOntEteEffectues'] = "<span class='valide'>Les modifications ont été apportées</span>";
$_trad['membre'] = "Membre"; 
$_trad['modifier'] = "Modifier";
$_trad['motPasseOublie'] = 'Vous avez oublié votre mot de passe?';
$_trad['numAdmInsufisant'] = "<span class='alert'>Vous est le seul administrateur du site!</span>";
$_trad['Out'] = "Annuler";
$_trad['pasDansMenu'] = " n'exisite pas dans le menu!";
$_trad['pasDansMenuAdmin'] = " n'exisite pas dans le menu Admin!";
$_trad['pasDansMenuFooter'] = " n'exisite pas dans le menu du pied de page!";
$_trad['pasDansMenuMembre'] = " n'exisite pas dans le menu des membres!";
$_trad['pasDeJeton'] = "Le Jeton n'est plus valide";
$_trad['pasEncoreMembre'] = " Pas encore membre? ";
$_trad['rectifier'] = "Rectifier";
$_trad['redirigeVerConnexion'] = "<h2>Bienvenu Sur le site de Lokisalle</h2><p>Vous serait redirigé ver la page de <a href='index.php?nav=actif'>connexion!</a>.</p>";
$_trad['reserver'] = "Reserver";
$_trad['revenir'] = "Revenir";
$_trad['select'] = "Sélectioner";
$_trad['valide'] = "Valider";
$_trad['validerInscription'] = "<h2>Bienvenu Sur le site de Lokisalle</h2>Merci de valider votre inscription en clicant sur le liens envoillé par mail";
$_trad['validerMail'] = "<h2>Bienvenu Sur le site de Lokisalle</h2>Merci de valider votre inscription en clicant sur ce liens";
$_trad['votreCompteLokisalle'] = "Votre Compte sur Lokisalle";
$_trad['vousNePouvezPasVousSupprimerVousMeme'] = "<span class='alert'>Vous ne pouvez pas vous supprimer!!</span>";