<?php

$_trad['-bienvenu'] = "<h2>Bienvenido al sitio LOKISALLE</h2>";
$_trad['-gestion'] = "<h2>Servicio en linea LOKISALLE</h2>";
/* trad pour les champs SQL */
$_trad['champ']['active'] = "Activar";
$_trad['champ']['adresse'] = "Direccion";
$_trad['champ']['capacite'] = "Capacidad";
$_trad['champ']['categorie'] = "Categoria";
$_trad['champ']['cp'] = "Codigo Postal";
$_trad['champ']['description'] = "Descripcion";
$_trad['champ']['email'] = "Correo electronico";
$_trad['champ']['gsm'] = "N°. celular";
$_trad['champ']['id_membre'] = "Identifiante";
$_trad['champ']['id_salle'] = "Identifiante";
$_trad['champ']['jeton'] = "Token";
$_trad['champ']['mdp'] = "Contraseña";
$_trad['champ']['nom'] = "Apellido";
$_trad['champ']['pays'] = "Pais";
$_trad['champ']['photo'] = "Foto";
$_trad['champ']['pos'] = "Posicion";
$_trad['champ']['prenom'] = "Nombre";
$_trad['champ']['pseudo'] = "Usuario";
$_trad['champ']['rapel'] = "Opcion";
$_trad['champ']['sexe'] = "Sexo";
$_trad['champ']['statut'] = "Statuto";
$_trad['champ']['telephone'] = "N°. telefonico";
$_trad['champ']['titre'] = "Titulo";
$_trad['champ']['valide'] = "Validar";
$_trad['champ']['ville'] = "Ciudad";

/* trad pour valeurs par defaut dans les formulaires */
$_trad['defaut']['ajouter'] = "Crear";
$_trad['defaut']['capacite'] = "Capacidad";
$_trad['defaut']['cp'] = "Zip 00";
$_trad['defaut']['description'] = "Descripcion...";
$_trad['defaut']['gsm'] = "08 12 34 56 78";
$_trad['defaut']['Inscription'] = "Inscribirse";
$_trad['defaut']['MiseAJ'] = "Actualizar";
$_trad['defaut']['modifier'] = "Modificar";
$_trad['defaut']['Monnom'] = "Mi apellido";
$_trad['defaut']['Monprenom'] = "Mi nombre";
$_trad['defaut']['MotPasse'] = "Contrasena!";
$_trad['defaut']['Ouhabite'] = "Donde vivo";
$_trad['defaut']['photo'] = "Foto";
$_trad['defaut']['SeConnecter'] = "Connectarse";
$_trad['defaut']['telephone'] = "03 89 76 43 21";
$_trad['defaut']['valider'] = "Validar";
$_trad['defaut']['ville'] = "Santiago...";

/* trad des messages d'erreurs dans les formulaires */
$_trad['erreur']['erreur'] = " Error ";
$_trad['erreur']['acces'] = " <span class='alert'>Ha hecho demaciadas tentativas de conexion<br>Por favor cierre su navegador y vuelva mas tarde !</span>";
$_trad['erreur']['aphanumeriqueSansSpace'] = " Valores aceptados: A à Z et 0 à 9 sans espaces ";
$_trad['erreur']['ATTENTIONErreurSurRequeteSQL'] = "<span style='color:red'>ATTENCION! Error SQL</span><br />";
$_trad['erreur']['ATTENTIONfaitQuoiAvec'] = " !!! CUIDADO !!!! Que hace usted con ";
$_trad['erreur']['ATTENTIONImpossibleFermerConnexionBDD'] = "<span style='color:red'>ATTENCION! Impossible de cerrar la conexion con la BDD</span><br /><b>Message : </b>";
$_trad['erreur']['caracteres'] = " letras y numeros ";
$_trad['erreur']['controlTelephone'] = " Por lo menos un N° de telefono debe ser indicado ";
$_trad['erreur']['corrigerErreurDans'] = " Por favor rectifique ";
$_trad['erreur']['deuxValeursDifferents'] = "Los dos valeures no son iguales para ";
$_trad['erreur']['doitAvoirNombreCaracterComprisEntre'] = " debe posser caracteres entre ";
$_trad['erreur']['doitContenir'] = " debe contener ";
$_trad['erreur']['doitContenirEntre'] = " debe contener entre ";
$_trad['erreur']['emailexistant'] = " <span class='alert'>! El correo electronico ya ha sido utilisado !</span>";
$_trad['erreur']['erreur404'] = "La pagina que solicita no existe!";
$_trad['erreur']['erreurConnexion'] = "<span class='alert'>No podemos identificarle <br>Por favor inrtroduzca nuevamente su informacion</span>";
$_trad['erreur']['erreurDansDimensionsImage']= "Error en las dimernciones de la imagen !";
$_trad['erreur']['erreurInterneEmpecheUplaodImage'] = "Un error interno impide la subida del fichero";
$_trad['erreur']['jetonExpire'] = "Su solicitud ha expirado!";
$_trad['erreur']['extensionFichierEstIncorrecte'] = "La extencion del fichero no es correcta !";
$_trad['erreur']['fichierUploaderNestPasUneImage'] = "El fichero no es una imagen !";
$_trad['erreur']['inconueConnexion'] = "<span class='alert'>Un error se ha producido </span>";
$_trad['erreur']['mailInexistant'] = "El mail no existe en nuestros registros!";
$_trad['erreur']['installData'] = "<span style='color:red'>ERROR FATAL!</span>";
$_trad['erreur']['leRepertoireNePeutEtreCree'] = "ERROR : la carpeta de imagenes no pudo ser creada !<br> Verifique si tiene los derechos suficientes para crearla manualmente !";
$_trad['erreur']['minimumAphaNumerique'] = " Debe haber un minimo de ";
$_trad['erreur']['nonVide'] = " Ne debe estar vacio ";
$_trad['erreur']['NULL'] = $_trad['erreur']['inconueConnexion'] . "<br/>La informacion que solicita no existe!";
$_trad['erreur']['obligatoire'] = " es obligatorio ";
$_trad['erreur']['problemeLorsUpload'] = "Problema en la subida del fichero !";
$_trad['erreur']['pseudoIndisponble'] = " <span class='alert'>! Usuario indisponible !</span> ";
$_trad['erreur']['queDesChiffres'] = " Solo se aceptan numeros";
$_trad['erreur']['redirigeVerConnection'] = "<h2>Bienvenido al sito de Lokisalle</h2><p style='color:red'>" . $_trad['erreur']['NULL'] . "</p><p>Sera usted dirigido a la pagina de <a href='index.php?nav=actif'>conexion!</a>.</p>";
$_trad['erreur']['reservationVide'] = "No hay ninguna sala seleccionada!";
$_trad['erreur']['statics'] = "El contenido no esta disponible!";
$_trad['erreur']['surLe'] = " Error con ";
$_trad['erreur']['uneErreurEstSurvenue'] = " A ocurrido un error en su conexion!";
$_trad['erreur']['validerInscriptionMail'] = "Debe validar su inscripcion con le mail que se le ha enviado a la direccion ";
$_trad['erreur']['veuillezDeRectifier'] = " Por favor rectifique ";
$_trad['erreur']['veuillezRemplirFormulaire'] = "Por favor llene el formulario !";
$_trad['erreur']['vousAvezOublieDeRectifier'] = " Ha olvidado rectificar ";
$_trad['erreur']['vousAvezUneErreurDans'] = " Tiene usted un error con ";
$_trad['erreur']['vousDevezChoisireUneOption'] = " Escoge una opcion ";

/* trad pour les menus */
$_trad['nav']['actif'] = "Conexion";
$_trad['nav']['ADMIN'] = "ADMIN";
$_trad['nav']['backoffice'] = "Administracion"; 
$_trad['nav']['boutique'] = "Negocio"; 
$_trad['nav']['cgv'] = "C.G.V"; 
$_trad['nav']['conditionsGeneralesVente'] = "Condiciones Generales de Venta";
$_trad['nav']['contact'] = "Contacto"; 
$_trad['nav']['detail'] = "Ficha"; 
$_trad['nav']['detailDuProduit'] = "Detalle del producto";
$_trad['nav']['editerSalles'] = "Fiche de salas";
$_trad['nav']['ficheMembre'] = "Ficha Usuario"; 
$_trad['nav']['ficheSalles'] = "Ficha de Salas"; 
$_trad['nav']['gestionSalles'] = "Salas";
$_trad['nav']['home'] = "Inicio"; 
$_trad['nav']['inscription'] = "Inscripcion"; 
$_trad['nav']['locationDesSalles'] = "Alquiler de salas";
$_trad['nav']['mdpperdu'] = "Recuperacion de contraseña";
$_trad['nav']['mentions'] = "Mentions legal"; 
$_trad['nav']['mentionsLegales'] = "Menciones legales";
$_trad['nav']['mesAchats'] = "Mis compras";
$_trad['nav']['mettreJourMesInformations'] = "Actualisar mis informaciones";
$_trad['nav']['mjprofil'] = "Actualisacion"; 
$_trad['nav']['monProfil'] = "Mi Perfil";
$_trad['nav']['MotDePasseOublie'] = "Contraseña olvidada";
$_trad['nav']['newsletter'] = "Inscribirse a la newsletter"; 
$_trad['nav']['nousContacter'] = "Contactarnos"; 
$_trad['nav']['out'] = "Desconexion";
$_trad['nav']['panier'] = "Carrito"; 
$_trad['nav']['plan'] = "Plano del sitio"; 
$_trad['nav']['profil'] = "Ver su perfil"; 
$_trad['nav']['recherche'] = "Buscar";
$_trad['nav']['reservation'] = "Réservacion";
$_trad['nav']['resultatDeVotreRecherche'] = "Resultado de busqueda";
$_trad['nav']['salles'] = "Salas"; 
$_trad['nav']['seInscrire'] = "Inscribirse";
$_trad['nav']['toutesNosOffres'] = "Todas nuestras ofertas";
$_trad['nav']['users'] = "Miembros"; 
$_trad['nav']['ventes'] = "Pedidos";

/* trad pour les titres des pages */
$_trad['titre']['actif'] = "";
$_trad['titre']['backoffice'] = "administracion";
$_trad['titre']['boutique'] = "tienda";
$_trad['titre']['cgv'] = "Condiciones Generales de Venta";
$_trad['titre']['validerMDP'] = "Validar contraseña";
$_trad['titre']['connection'] = "conectarse";
$_trad['titre']['contact'] = "contacto";
$_trad['titre']['detail'] = "Fiche Producto";
$_trad['titre']['editerSalles'] = "Modificar sala";
$_trad['titre']['erreur404'] = "ERROR 404";
$_trad['titre']['ficheMembre'] = "Ficha Miembro";
$_trad['titre']['ficheSalles'] = "Ficha Salla LOKISALLE";
$_trad['titre']['gestionSalles'] = "Gestion des salas";
$_trad['titre']['home'] = "Locacion de salas LOKISALLE";
$_trad['titre']['inscription'] = "inscripcion";
$_trad['titre']['mdpperdu'] = "Contraseña Perdida?";
$_trad['titre']['mentions'] = "Menciones legales";
$_trad['titre']['mjprofil'] = "ponerme al dia";
$_trad['titre']['newsletter'] = "newsletter";
$_trad['titre']['out'] = "";
$_trad['titre']['panier'] = "compras";
$_trad['titre']['plan'] = "nuestras rubricas";
$_trad['titre']['profil'] = "perfil";
$_trad['titre']['recherche'] = "Resultado de la busqueda";
$_trad['titre']['reservation'] = "Todas nuestras ofertas";
$_trad['titre']['salles'] = "LOKISALLE"; 
$_trad['titre']['users'] = "Miembros";
$_trad['titre']['validerInscription'] = "Validacion de inscripcion";
$_trad['titre']['ventes'] = "pedidos";

/* trad pour les Valeurs des options BDD */
//$_trad['value']['ADM'] = "ADMINISTRADOR";
$_trad['value']['C'] = "Conferencias";
//$_trad['value']['COL'] = "COLABORADOR";
$_trad['value']['F'] = "Eventos";
$_trad['value']['f'] = "Mujer";
$_trad['value']['indefini'] = "Indefinido(a)";
$_trad['value']['m'] = "Hombre";
$_trad['value']['MEM'] = "MIEMBRO";
$_trad['value']['R'] = "Reuniones";
$_trad['value']['on'] = "Acordarse de mi";

/* trad pour les autres textes */
$_trad['activer'] = "Activar";
$_trad['admin'] = "Adminitrador";
$_trad['ajouterSalle'] = "Agresar una sala <a href=" . LINK . "?nav=editerSalles>AGREGAR</a>";
$_trad['Bonjour'] = "Apreciado";
$_trad['delete'] = "Suprimir";
$_trad['demandeDeMotPasse'] = 'Solicitud de contraseña';
$_trad['dernieresOffres'] = "Oportunidades";
$_trad['enConstruccion'] =  "En construccion!";
$_trad['enlever'] = "Retirar";
$_trad['ERRORSaisie'] = "Por favor corrija el o los Errores en el formulario";
$_trad['indefinie'] = "<span class='alert'>Indefinido</span>";
$_trad['inscriptionLokisalle'] = "Inscripcion Lokisalle";
$_trad['inscrivezVous'] = " Inscribete ";
$_trad['laRubrique'] = "La rubrica ";
$_trad['lesModificationOntEteEffectues'] = "<span class='valide'>Las modificaciones han sido aportadas</span>";
$_trad['membre'] = "Miembro"; 
$_trad['modifier'] = "Modificar";
$_trad['motPasseOublie'] = 'Ha olvidado su contraseña?';
$_trad['numAdmInsufisant'] = "<span class='alert'>Es usted el unico administrador del sitio !</span>";
$_trad['Out'] = "Regresar";
$_trad['pasDansMenu'] = " no existe dentro de los paràmetros del menu!";
$_trad['pasDansMenuAdmin'] = " no existe dentro de los paràmetros del menu del Administrador!";
$_trad['pasDansMenuFooter'] = " no existe dentro de los paràmetros del menu del pied de pagina!";
$_trad['pasDansMenuMembre'] = " no existe dentro de los paràmetros del menu de miembros!";
$_trad['pasEncoreMembre'] = "Aun no es miembro? ";
$_trad['personnes'] = " personnas ";
$_trad['priseEnCompteMDP'] = "Su Contraseña sera reiniticializada al validar su informacion con el link enviado a la direccion mail de registro.";;
$_trad['rectifier'] = "Rectificar";
$_trad['redirigeVerConnection'] = $_trad['-bienvenu'] . "<p>Sera usted dirigido a la pagina de <a href='index.php?nav=actif'>conexion!</a>.</p>";
$_trad['reservationOk'] = "Lista de reservationes";
$_trad['reserver'] = "Reservar";
$_trad['revenir'] = "Regresar";
$_trad['select'] = "Selectionar";
$_trad['valide'] = "Validar";
$_trad['validerChangementMotPasse'] = $_trad['-gestion'] . "Por Favor valide su solicitud de cambio de Contraseña clicando aqui";
$_trad['validerInscription'] = $_trad['-bienvenu'] . "Su inscription sera activada al validar su informacion con el link enviado a la direccion mail de registro.";
$_trad['validerInscriptionMail'] = $_trad['-bienvenu'] . "Por Favor valide su inscripcion clicando aqui";
$_trad['votreCompteLokisalle'] = "Su cuenta en Lokisalle";
$_trad['vousNePouvezPasVousSupprimerVousMeme'] = "<span class='alert'>No puede usted suprimirse a si mismo!!</span>";